### ISSUE TITLE
Port in CLA code from aicore/contributor-license-agreement

### ISSUE THREAD

**Issue by abose** [brackets-cont/contributor-license-agreement#1]
- [x] Copy in CLA infrastructure from https://github.com/aicore/contributor-license-agreement
- [x] Remove all license text from personal and employer CLA
- [x] Remove existing signatories from aicore CLA

## Notes
License and Copyright to brackets granted for CLA framework by aicore: https://github.com/aicore/contributor-license-agreement/issues/44

**Comment by psdhanesh7** [comment]
Issue solved.
Tasks completed in pull request #6.
