### ISSUE TITLE
Update CLA text for personal and employer CLA

### ISSUE THREAD

**Issue by abose** [brackets-cont/contributor-license-agreement#2]
- [x] Use CLA template from https://opensource.adobe.com/cla.html
- [x] Update personal cla, change to `Brackets community (brackets.io)` instead of Adobe in license terms.
- [x] update employer cla, change to `Brackets community (brackets.io)` instead of Adobe in license terms.

**Comment by psdhanesh7** [comment]
> * [x]  Use CLA template from https://opensource.adobe.com/cla.html
> * [x]   Update personal cla, change to `Brackets community (brackets.io)` instead of Adobe in license terms.
> * [x]  update employer cla, change to `Brackets community (brackets.io)` instead of Adobe in license terms.

Issue solved.
Tasks completed in pull request #6
