### ISSUE TITLE
Upgrade CLA check scripts from aicore/contributor-license-agreement

### ISSUE THREAD

**Issue by abose** [brackets-cont/contributor-license-agreement#20]
- [x] New features added to CLA check infra from https://github.com/aicore/contributor-license-agreement should be imported into this repo for brackets
- [x] Validate features are working as expected (comment bots, cla sign check use cases)

**Comment by psdhanesh7** [comment]
> * [x]  New features added to CLA check infra from https://github.com/aicore/contributor-license-agreement should be imported into this repo for brackets
> * [x]  Validate features are working as expected (comment bots, cla sign check use cases)
>* Task 1: Completed with pull requests https://github.com/brackets-cont/contributor-license-agreement/pull/21#issue-1221721400 and https://github.com/brackets-cont/contributor-license-agreement/pull/24#issue-1221781271
>* Task 2: Verified changes are working as expected in pull request https://github.com/brackets-cont/contributor-license-agreement/pull/25#issue-1221785071

**Comment by abose** [comment]
Thanks for fixing the issue @psdhanesh7
