### ISSUE TITLE
Integrate welcom bot

### ISSUE THREAD

**Issue by abose** [brackets-cont/contributor-license-agreement#3]
- [x] Integrate welcome bot to welcome new members. https://github.com/apps/welcome
- [x] See the messaging examples from https://github.com/aicore/contributor-license-agreement/pull/43

**Comment by psdhanesh7** [comment]
> * [ x ]  Integrate welcome bot to welcome new members. https://github.com/apps/welcome
> * [ x ]  See the messaging examples from [Update personal_contributor_licence_agreement.md aicore/contributor-license-agreement#43](https://github.com/aicore/contributor-license-agreement/pull/43)

Tasks completed in pull request #7.
Testing to be done.

**Comment by abose** [comment]
Changes merged. Waiting for the next pull request to validate changes.

**Comment by abose** [comment]
Verified working in https://github.com/brackets-cont/contributor-license-agreement/pull/8
Thanks, @psdhanesh7 for the changes!
